### ISSUE TITLE
AUTH_KEY_UNREGISTERED

### ISSUE THREAD

**Issue by pcegarra** [abdhass/telegram-channel-scraper#1]
Error 401 AUTH_KEY_UNREGISTERED 2 4

any idea why im getting this error?

**Comment by pcegarra** [comment]
Yes, the first time it was working ok, but I try again and I get the error

**Comment by abdhass** [comment]
Version 3 of the mt-telegram library should fix it. Just about to try it soon.

**Comment by karianpour** [comment]
The problem is that we run 2 async functions,

- node-storage.js (login process)
- index.js (scrapping process)

first we have to login and then start the scrapping, but as we do not await for the login process, scrapping process might start earlier, then you get "AUTH_KEY_UNREGISTERED".

The solution is to await for it.

I am creating a pull request for it.

**Comment by abdhass** [comment]
@karianpour many thanks for your pull request and your time. Much appreciated. Merged

**Comment by HansHauge** [comment]
I have the latest version of the code and I'm still getting the error. Any ideas?

**Comment by martyns0n** [comment]
> I have the latest version of the code and I'm still getting the error. Any ideas?

Same issue

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/20739202/56276839-eff73180-610b-11e9-9316-4d10bf169e55.png">

**Comment by abdhass** [comment]
I'll have a look at this today and get back to you all. Thanks

**Comment by martyns0n** [comment]
After sign out and sign in I got this error

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/20739202/56278705-65183600-610f-11e9-87b0-ec391c874fe9.png">
